export enum NOS_ENDPOINTS {
    algemeen = "https://nos.nl/nieuws/archief",
    binnenland = "https://nos.nl/nieuws/binnenland/archief",
    buitenland = "https://nos.nl/nieuws/buitenland/archief",
    regio = "https://nos.nl/nieuws/regio/archief",
    politiek = "https://nos.nl/nieuws/politiek/archief",
    economie = "https://nos.nl/nieuws/economie/archief",
    koningshuis = "https://nos.nl/nieuws/koningshuis/archief",
    tech = "https://nos.nl/nieuws/tech/archief",
    "cultuur-en-media" = "https://nos.nl/nieuws/cultuur-en-media/archief",
    opmerkelijk = "https://nos.nl/nieuws/opmerkelijk/archief",
    sport = "https://nos.nl/sport/archief",
    voetbal = "https://nos.nl/sport/voetbal/archief",
    "formule-1" = "https://nos.nl/sport/formule-1/archief",
    wielrennen = "https://nos.nl/sport/wielrennen/archief",
    tennis = "https://nos.nl/sport/tennis/archief",
}
